include: package:flutter_lints/flutter.yaml

linter:
  # https://dart.dev/guides/language/analysis-options
  rules:
    directives_ordering: true
    prefer_relative_imports: true
    prefer_single_quotes: true
