name: mini_counter
description: A very simple counter app
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  provider: ^6.0.5
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  drift_dev: ^2.13.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
