name: mini_counter
description: A very simple counter app
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  provider: ^6.0.5
  modal_bottom_sheet: ^3.0.0-pre
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  drift_dev: ^2.13.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# https://pub.dev/packages/intl_utils
#
# To generate intl code from arb files use this command:
# flutter pub run intl_utils:generate
#
# Or just install plugins for your IDE (VSCode or Android Studio)
flutter_intl:
  enabled: true
  arb_dir: lib/presentation/intl/l10n
  output_dir: lib/presentation/intl/generated
  main_locale: en

# To recreate launcher icons use this command:
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#fafafa"
  adaptive_icon_foreground: "assets/logo/logo-transparent-padding.png"